from abc import ABC, abstractmethod
class SimulatedRocket(ABC):
    #Use this Interface to guide what the SimulatedRocket software needs to do
    @abstractmethod
    def getAccelerometerValue(self) -> float:
        '''Outputs a float representing the value of the rocket's acceleration at that given time slice'''
        pass
    @abstractmethod
    def getGyroscopeValue(self) -> list:
        '''Outputs an array of 3 floating point numbers that represent the pitch, yaw and roll angular velocities measured
        by the gyroscope on the rocket
        Outputs Pitch, Yaw, then Roll angular velocity'''
        pass
    @abstractmethod 
    def getAltitude(self) -> float:
        '''Outputs a float representing the value of the rocket's altitude at that given time slice'''
        pass
    @abstractmethod
    def getEncoderValues(self) -> list:
        '''Outputs an array of 4 floating point numbers representing encoder values for the 4 motor controllers controlling the 
        canards'''
        pass
    @abstractmethod
    def setControlOutputs(self, list) -> None:
        '''Gets an array of 4 floating point numbers that represent control output values for the 4 motor controllers 
        generated by the PD control loop'''
        pass
    def advanceOneTimeSlice(self, time_slice: int) -> None:
        '''Causes the simulation to advance by the given time_slice'''
        pass




